//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_work {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Eng() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("course_work.Eng", typeof(Eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crossover is the Genetic Algorithm’s distinguishing
        ///feature. It involves mixing and matching parts of two
        ///parents to form children. Let’s say the vectors are of length l. Two-point crossover implies picking two numbers c and d, and swap the indexes between them. When c = d you get an empty crossover (with 1/l probability). .
        /// </summary>
        internal static string algoinfo {
            get {
                return ResourceManager.GetString("algoinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на algorithm info.
        /// </summary>
        internal static string algorithmToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("algorithmToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на random.
        /// </summary>
        internal static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на with my points.
        /// </summary>
        internal static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на do crossover.
        /// </summary>
        internal static string button4_Text {
            get {
                return ResourceManager.GetString("button4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на again.
        /// </summary>
        internal static string button5_Text {
            get {
                return ResourceManager.GetString("button5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на exit.
        /// </summary>
        internal static string button6_Text {
            get {
                return ResourceManager.GetString("button6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на course work info.
        /// </summary>
        internal static string courseWorkInfoToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("courseWorkInfoToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на two-point crossover .
        /// </summary>
        internal static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на help.
        /// </summary>
        internal static string helpToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на info.
        /// </summary>
        internal static string infoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("infoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на enter 1st and 2nd chromosome (1 and 0, delimited by spases).
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на enter length of chromosomes and press &quot;ok&quot; to generate ramdom chromosome of this length.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на new chromosomes are:.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1st and 2nd points.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на choose type of crossover.
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на language.
        /// </summary>
        internal static string languageToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на doing algorithm.
        /// </summary>
        internal static string Mainbutton1_Text {
            get {
                return ResourceManager.GetString("Mainbutton1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на animated work of algorithm.
        /// </summary>
        internal static string Mainbutton2_Text {
            get {
                return ResourceManager.GetString("Mainbutton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на course work.
        /// </summary>
        internal static string mainform {
            get {
                return ResourceManager.GetString("mainform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To do crossover you must enter 2 chromosomes (1 and 0, delimited by spases) or generate them randomly (enter length and ckick &quot;ok&quot;), choose the way for generating crossower points (random or enter in spesial place) and press button &quot;do crossover&quot;. The result chromosomes will appear lower. Press &quot;again&quot; to clear all and try next chromosomes. Press &quot;exit&quot; to close window..
        /// </summary>
        internal static string text1 {
            get {
                return ResourceManager.GetString("text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на error in entered points.
        /// </summary>
        internal static string text2 {
            get {
                return ResourceManager.GetString("text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на chromosomes can&apos;t be zero length.
        /// </summary>
        internal static string text3 {
            get {
                return ResourceManager.GetString("text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на chromosomes must be of equal length.
        /// </summary>
        internal static string text4 {
            get {
                return ResourceManager.GetString("text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на something wrong with format of chromosomes.
        /// </summary>
        internal static string text5 {
            get {
                return ResourceManager.GetString("text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на chromosomes can contain only 0 and 1!.
        /// </summary>
        internal static string text6 {
            get {
                return ResourceManager.GetString("text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на points must be less then length of chromosomes.
        /// </summary>
        internal static string text7 {
            get {
                return ResourceManager.GetString("text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To do crossover you must enter the length of chromosomes and press &quot;ok&quot;. Then the program will generate random chromosomes and draw them (different colors for visibility). Every click to &quot;do crossover&quot; will cause new randomly generated animated crossover. to choose another length and generate new chromosomes click &quot;again&quot;, to close the window press &quot;exit&quot;..
        /// </summary>
        internal static string textinfoform2 {
            get {
                return ResourceManager.GetString("textinfoform2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This program is a course work on subject OOP with tesis &quot;Realization of algorithm on C# and visualization of it&quot;. Done by Ofitserova Tatiana (student of group M8O-209B-19)..
        /// </summary>
        internal static string workinfo {
            get {
                return ResourceManager.GetString("workinfo", resourceCulture);
            }
        }
    }
}
