//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_work {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rus() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("course_work.Rus", typeof(Rus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кроссовер это отличительная черта генетического алгоритма. Он включает в себя перемешивания и сочетания частей хромосом двух родителей для получения хромосом детей. Скажем, что векторы имеют длину l. Кроссовер с двумя точками подразумевает взятие двух чисел c и d и обмен индексами между ними.в случае, если c=d происходит пустой кроссовер (с вероятностью 1/l)..
        /// </summary>
        internal static string algoinfo {
            get {
                return ResourceManager.GetString("algoinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на про алгоритм.
        /// </summary>
        internal static string algorithmToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("algorithmToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на случайный.
        /// </summary>
        internal static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на с моими точками.
        /// </summary>
        internal static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кроссовер.
        /// </summary>
        internal static string button4_Text {
            get {
                return ResourceManager.GetString("button4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на еще раз.
        /// </summary>
        internal static string button5_Text {
            get {
                return ResourceManager.GetString("button5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выход.
        /// </summary>
        internal static string button6_Text {
            get {
                return ResourceManager.GetString("button6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на про работу.
        /// </summary>
        internal static string courseWorkInfoToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("courseWorkInfoToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кроссовер с двумя точками .
        /// </summary>
        internal static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на помощь.
        /// </summary>
        internal static string helpToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на инфо.
        /// </summary>
        internal static string infoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("infoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите первую и вторую хромосому (1 и 0, разделенные пробелами).
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите длину хромосом и нажмите &quot;ок&quot; для генерации случайных хромосом заданной длины.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на итоговые хромосомы:.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1я и вторая точки.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выберите тип кроссовера.
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на язык.
        /// </summary>
        internal static string languageToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на работать с алгоритмом.
        /// </summary>
        internal static string Mainbutton1_Text {
            get {
                return ResourceManager.GetString("Mainbutton1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на анимированная работа алгоритма.
        /// </summary>
        internal static string Mainbutton2_Text {
            get {
                return ResourceManager.GetString("Mainbutton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на курсовая работа.
        /// </summary>
        internal static string mainform {
            get {
                return ResourceManager.GetString("mainform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выполнения алгоритма требуется ввести две хромосомы, состоящие из нулей и единиц, разделенных пробелами (или сгенерировать случайные хромосомы путем выбора количества элементов в них и нажатия кнопки &quot;ок&quot;), выбрать способ генерации точек кроссовера (случайные или ввести собственные) и нажать кнопку &quot;кроссовер&quot;. Результат появится в нижнем окне. Чтобы выйти из программы требуется нажать &quot;выход&quot;. Чтобы очистить поля и повторить алгоритм - нажать &quot;еще раз&quot;..
        /// </summary>
        internal static string text1 {
            get {
                return ResourceManager.GetString("text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка в введенных точках.
        /// </summary>
        internal static string text2 {
            get {
                return ResourceManager.GetString("text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на хромосома не может быть нулевой длины :(.
        /// </summary>
        internal static string text3 {
            get {
                return ResourceManager.GetString("text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на хромосомы должны быть одной длины :(.
        /// </summary>
        internal static string text4 {
            get {
                return ResourceManager.GetString("text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на что-то не так с форматом введенных данных.
        /// </summary>
        internal static string text5 {
            get {
                return ResourceManager.GetString("text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на в хромосоме могут быть только 0 и 1!.
        /// </summary>
        internal static string text6 {
            get {
                return ResourceManager.GetString("text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на точка не может выходить за границу хромосомы.
        /// </summary>
        internal static string text7 {
            get {
                return ResourceManager.GetString("text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выполнения алгоритма необкодимо ввести длину требуемых хромосом и нажать &quot;ок&quot;, после чего отобразятся рандомно сгенерированные хромосомы (разных цветов для наглядности). При каждом нажатии кнопки &quot;кроссовер&quot; будет выполняться случайный анимированный кроссовер, при нажатии кнопки &quot;еще раз&quot; появится возможность выбрать новую длину и создать новые хромосомы. После нажатия &quot;выход&quot; окно закроется..
        /// </summary>
        internal static string textinfoform2 {
            get {
                return ResourceManager.GetString("textinfoform2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная программа является курсовой работой по предмету Объектно-ориентированное программирование по теме &quot;Реализация алгоритма на С# и его визуализация&quot;, выполненной Офицеровой Татьяной, студенткой группы М8О-209Б-19. .
        /// </summary>
        internal static string workinfo {
            get {
                return ResourceManager.GetString("workinfo", resourceCulture);
            }
        }
    }
}
